[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['pip install --no-cache-dir -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'bash start_production.sh'
