"""enhance_groups_with_context

Revision ID: 0089593d7775
Revises: c8bed965152a
Create Date: 2025-09-19 20:31:20.789332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0089593d7775'
down_revision = 'c8bed965152a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_memberships', sa.Column('group_type', sa.Enum('DEPARTMENT', 'ROLE', 'ACCESS_LEVEL', 'LOCATION', 'PROJECT', 'SECURITY_CLEARANCE', 'EMPLOYMENT_TYPE', 'TEAM', name='grouptypeenum'), nullable=False))
    op.add_column('group_memberships', sa.Column('description', sa.String(), nullable=True))
    op.add_column('group_memberships', sa.Column('source_system', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_memberships', 'source_system')
    op.drop_column('group_memberships', 'description')
    op.drop_column('group_memberships', 'group_type')
    # ### end Alembic commands ###
