"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2024-12-16 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_identities',
    sa.Column('cid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='statusenum'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('accounts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='statusenum'), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('cid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['canonical_identities.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('compliant', sa.Boolean(), nullable=False),
    sa.Column('owner_cid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_cid'], ['canonical_identities.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_memberships',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cid'], ['canonical_identities.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_memberships')
    op.drop_table('devices')
    op.drop_table('accounts')
    op.drop_table('canonical_identities')
    op.execute('DROP TYPE statusenum')
    # ### end Alembic commands ###
