"""add_access_management_tables

Revision ID: b350b231ce0f
Revises: 0089593d7775
Create Date: 2025-09-22 15:42:59.677639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b350b231ce0f'
down_revision = '0089593d7775'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_type', sa.String(), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=True),
    sa.Column('users_in_scope', sa.JSON(), nullable=True),
    sa.Column('systems_in_scope', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('primary_reviewer', sa.String(), nullable=False),
    sa.Column('secondary_reviewers', sa.JSON(), nullable=True),
    sa.Column('total_access_reviewed', sa.Integer(), nullable=True),
    sa.Column('access_certified', sa.Integer(), nullable=True),
    sa.Column('access_revoked', sa.Integer(), nullable=True),
    sa.Column('access_flagged', sa.Integer(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('exceptions', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_framework', sa.String(), nullable=True),
    sa.Column('auditor_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_cid', sa.UUID(), nullable=False),
    sa.Column('access_type', sa.Enum('SYSTEM_ACCESS', 'APPLICATION_ACCESS', 'DATA_ACCESS', 'NETWORK_ACCESS', 'PHYSICAL_ACCESS', 'ADMINISTRATIVE_ACCESS', 'API_ACCESS', 'DATABASE_ACCESS', name='accesstypeenum'), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('resource_identifier', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Enum('JOB_REQUIREMENT', 'PROJECT_ASSIGNMENT', 'TEMPORARY_ASSIGNMENT', 'ROLE_CHANGE', 'EMERGENCY_ACCESS', 'CONTRACTOR_ACCESS', 'EMPLOYMENT_TERMINATED', 'ROLE_CHANGED', 'PROJECT_COMPLETED', 'ACCESS_NO_LONGER_NEEDED', 'SECURITY_VIOLATION', 'POLICY_VIOLATION', 'EXPIRED_ACCESS', 'ADMIN_REVOCATION', name='accessreasonenum'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', 'SUSPENDED', 'PENDING_APPROVAL', 'PENDING_REVOCATION', name='accessstatusenum'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(), nullable=True),
    sa.Column('revocation_reason', sa.Enum('JOB_REQUIREMENT', 'PROJECT_ASSIGNMENT', 'TEMPORARY_ASSIGNMENT', 'ROLE_CHANGE', 'EMERGENCY_ACCESS', 'CONTRACTOR_ACCESS', 'EMPLOYMENT_TERMINATED', 'ROLE_CHANGED', 'PROJECT_COMPLETED', 'ACCESS_NO_LONGER_NEEDED', 'SECURITY_VIOLATION', 'POLICY_VIOLATION', 'EXPIRED_ACCESS', 'ADMIN_REVOCATION', name='accessreasonenum'), nullable=True),
    sa.Column('revocation_justification', sa.Text(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_by', sa.String(), nullable=True),
    sa.Column('next_review_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_emergency_access', sa.Boolean(), nullable=True),
    sa.Column('emergency_ticket', sa.String(), nullable=True),
    sa.Column('emergency_approver', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('compliance_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_cid'], ['canonical_identities.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_cid', sa.UUID(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('access_frequency', sa.String(), nullable=True),
    sa.Column('typical_access_times', sa.JSON(), nullable=True),
    sa.Column('typical_access_duration', sa.String(), nullable=True),
    sa.Column('access_locations', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('anomaly_indicators', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.Column('pattern_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pattern_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_cid'], ['canonical_identities.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_grant_id', sa.UUID(), nullable=True),
    sa.Column('user_cid', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('ACCESS_GRANTED', 'ACCESS_REVOKED', 'ACCESS_MODIFIED', 'ACCESS_SUSPENDED', 'ACCESS_RESTORED', 'ACCESS_REVIEWED', 'ACCESS_EXPIRED', 'EMERGENCY_ACCESS', 'BULK_ACCESS_CHANGE', name='auditactionenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('resource_identifier', sa.String(), nullable=True),
    sa.Column('access_type', sa.Enum('SYSTEM_ACCESS', 'APPLICATION_ACCESS', 'DATA_ACCESS', 'NETWORK_ACCESS', 'PHYSICAL_ACCESS', 'ADMINISTRATIVE_ACCESS', 'API_ACCESS', 'DATABASE_ACCESS', name='accesstypeenum'), nullable=False),
    sa.Column('access_level', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('reason', sa.Enum('JOB_REQUIREMENT', 'PROJECT_ASSIGNMENT', 'TEMPORARY_ASSIGNMENT', 'ROLE_CHANGE', 'EMERGENCY_ACCESS', 'CONTRACTOR_ACCESS', 'EMPLOYMENT_TERMINATED', 'ROLE_CHANGED', 'PROJECT_COMPLETED', 'ACCESS_NO_LONGER_NEEDED', 'SECURITY_VIOLATION', 'POLICY_VIOLATION', 'EXPIRED_ACCESS', 'ADMIN_REVOCATION', name='accessreasonenum'), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('emergency_ticket', sa.String(), nullable=True),
    sa.Column('emergency_approver', sa.String(), nullable=True),
    sa.Column('compliance_tags', sa.JSON(), nullable=True),
    sa.Column('risk_assessment', sa.String(), nullable=True),
    sa.Column('record_hash', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('is_sealed', sa.Boolean(), nullable=True),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sealed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['access_grant_id'], ['access_grants.id'], ),
    sa.ForeignKeyConstraint(['user_cid'], ['canonical_identities.cid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_audit_logs')
    op.drop_table('access_patterns')
    op.drop_table('access_grants')
    op.drop_table('access_reviews')
    # ### end Alembic commands ###
